spring:
  profiles:
    active: local
  config:
    import: resource-local.yml

spring.main.allow-circular-references: true

some:
  some-name: local
  is-enabled: true
  some-nested-property:
    some-nested-name: nested-test
    some-nested-list: a,b,c,e,d

example-bean:
  list:
    - name: xbean
      value: 11111
    - name: ybean
      value: 22222
    - name: zbean
      value: 33333

profiles:
  name: local
  data: 1
---
spring:
  config:
    activate:
      on-profile: test
    import: resource-test.yml

profiles:
  name: test
  data: 2

